/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DevSideDrawer {
        "mainTitle": string;
        "open": boolean;
        "openDrawer": () => Promise<void>;
    }
    interface StockPrice {
    }
    interface ToolTip {
        "text": string;
    }
}
declare global {
    interface HTMLDevSideDrawerElement extends Components.DevSideDrawer, HTMLStencilElement {
    }
    var HTMLDevSideDrawerElement: {
        prototype: HTMLDevSideDrawerElement;
        new (): HTMLDevSideDrawerElement;
    };
    interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {
    }
    var HTMLStockPriceElement: {
        prototype: HTMLStockPriceElement;
        new (): HTMLStockPriceElement;
    };
    interface HTMLToolTipElement extends Components.ToolTip, HTMLStencilElement {
    }
    var HTMLToolTipElement: {
        prototype: HTMLToolTipElement;
        new (): HTMLToolTipElement;
    };
    interface HTMLElementTagNameMap {
        "dev-side-drawer": HTMLDevSideDrawerElement;
        "stock-price": HTMLStockPriceElement;
        "tool-tip": HTMLToolTipElement;
    }
}
declare namespace LocalJSX {
    interface DevSideDrawer {
        "mainTitle"?: string;
        "open"?: boolean;
    }
    interface StockPrice {
    }
    interface ToolTip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "dev-side-drawer": DevSideDrawer;
        "stock-price": StockPrice;
        "tool-tip": ToolTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dev-side-drawer": LocalJSX.DevSideDrawer & JSXBase.HTMLAttributes<HTMLDevSideDrawerElement>;
            "stock-price": LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
            "tool-tip": LocalJSX.ToolTip & JSXBase.HTMLAttributes<HTMLToolTipElement>;
        }
    }
}
